version: '3'

tasks:
  build:
    cmds:
      - go build -o app.exe cmd/server/main.go
  test:
    cmds:
      - go test -v ./...

  lint:
    cmds:
      - golangci-lint run

  run:
    cmds:
      - docker-compose up --build

  integration-test:
    cmds: 
      - docker-compose up -d db
      - go test -v ./... -tags=integration
    env: 
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_TABLE: postgres
      DB_HOST: localhost
      DB_PORT: '5432'
      DB_NAME: postgres
      SSL_MODE: disable